export const WORLD_LIMIT = 245;
export const ISLANDS = [
  {
    id: 'haven',
    name: 'Littlehaven',
    x: -30,
    z: -24,
    radius: 19,
    biome: 'shoals',
    color: '#529e64',
    port: { x: -9, z: -7 },
    description: 'A familiar light at the edge of the sea.',
  },
  {
    id: 'coral',
    name: 'Coral Crown',
    x: 85,
    z: -62,
    radius: 17,
    biome: 'reef',
    color: '#62ae75',
    port: { x: 64, z: -51 },
    description: 'A garden of coral, humming with life.',
  },
  {
    id: 'kelp',
    name: 'The Green Veil',
    x: -120,
    z: 47,
    radius: 18,
    biome: 'kelp',
    color: '#3c8069',
    port: { x: -100, z: 59 },
    description: 'Long green forests hide forgotten things.',
  },
  {
    id: 'moon',
    name: 'Moonwake Atoll',
    x: 145,
    z: 91,
    radius: 20,
    biome: 'moon',
    color: '#6993ae',
    port: { x: 123, z: 97 },
    description: 'When daylight fades, the reef awakens.',
  },
  {
    id: 'ember',
    name: 'Ember Reach',
    x: -105,
    z: -153,
    radius: 23,
    biome: 'volcanic',
    color: '#777977',
    port: { x: -79, z: -143 },
    description: 'Warm currents rise from a restless seabed.',
  },
  {
    id: 'abyss',
    name: 'The Quiet Deep',
    x: 51,
    z: -193,
    radius: 12,
    biome: 'abyss',
    color: '#827e9e',
    port: { x: 35, z: -178 },
    description: 'An ancient keeper waits beneath the waves.',
  },
  {
    id: 'drift',
    name: 'Driftwood Cay',
    x: -13,
    z: 145,
    radius: 14,
    biome: 'shoals',
    color: '#8ca968',
    port: { x: 5, z: 150 },
    description: 'A resting place for voyagers and stories.',
  },
] as const;
export const SPOTS = [
  { x: 6, z: -6, biome: 'shoals', depth: 12 },
  { x: -40, z: 24, biome: 'shoals', depth: 15 },
  { x: 63, z: -24, biome: 'reef', depth: 24 },
  { x: 111, z: -77, biome: 'reef', depth: 30 },
  { x: -85, z: 35, biome: 'kelp', depth: 32 },
  { x: -145, z: 75, biome: 'kelp', depth: 38 },
  { x: 107, z: 76, biome: 'moon', depth: 45 },
  { x: 165, z: 124, biome: 'moon', depth: 50 },
  { x: -66, z: -117, biome: 'volcanic', depth: 60 },
  { x: -144, z: -165, biome: 'volcanic', depth: 65 },
  { x: 24, z: -154, biome: 'abyss', depth: 85 },
  { x: 77, z: -168, biome: 'abyss', depth: 90 },
  { x: 15, z: 114, biome: 'shoals', depth: 18 },
];
export const SPECIES = [
  {
    id: 'sprat',
    name: 'Sunstripe sprat',
    biome: 'shoals',
    color: '#f3bc59',
    price: 24,
    w: 2,
    h: 1,
    level: 0,
    rarity: 'Common',
    night: false,
  },
  {
    id: 'bream',
    name: 'Bluefin bream',
    biome: 'shoals',
    color: '#79cce0',
    price: 38,
    w: 2,
    h: 2,
    level: 0,
    rarity: 'Common',
    night: false,
  },
  {
    id: 'clown',
    name: 'Apricot clownfish',
    biome: 'reef',
    color: '#f88e64',
    price: 48,
    w: 2,
    h: 1,
    level: 0,
    rarity: 'Uncommon',
    night: false,
  },
  {
    id: 'parrot',
    name: 'Jade parrotfish',
    biome: 'reef',
    color: '#5ddebb',
    price: 76,
    w: 3,
    h: 2,
    level: 1,
    rarity: 'Uncommon',
    night: false,
  },
  {
    id: 'perch',
    name: 'Ribbon perch',
    biome: 'kelp',
    color: '#b2c965',
    price: 52,
    w: 2,
    h: 2,
    level: 0,
    rarity: 'Uncommon',
    night: false,
  },
  {
    id: 'eel',
    name: 'Velvet ribbon eel',
    biome: 'kelp',
    color: '#bca0de',
    price: 90,
    w: 4,
    h: 1,
    level: 1,
    rarity: 'Rare',
    night: false,
  },
  {
    id: 'lantern',
    name: 'Moonlit lanternfish',
    biome: 'moon',
    color: '#9de9f4',
    price: 130,
    w: 2,
    h: 2,
    level: 1,
    rarity: 'Rare',
    night: true,
  },
  {
    id: 'ray',
    name: 'Starlace ray',
    biome: 'moon',
    color: '#b8a4ef',
    price: 170,
    w: 3,
    h: 2,
    level: 2,
    rarity: 'Rare',
    night: true,
  },
  {
    id: 'ruby',
    name: 'Ruby rockfish',
    biome: 'volcanic',
    color: '#ef836d',
    price: 140,
    w: 3,
    h: 2,
    level: 1,
    rarity: 'Rare',
    night: false,
  },
  {
    id: 'emberfin',
    name: 'Emberfin',
    biome: 'volcanic',
    color: '#fabb68',
    price: 205,
    w: 3,
    h: 1,
    level: 2,
    rarity: 'Rare',
    night: true,
  },
  {
    id: 'glass',
    name: 'Glassheart angler',
    biome: 'abyss',
    color: '#8ddede',
    price: 230,
    w: 3,
    h: 2,
    level: 2,
    rarity: 'Exotic',
    night: false,
  },
  {
    id: 'keeper',
    name: 'Luminous keeper',
    biome: 'abyss',
    color: '#d0b1ff',
    price: 520,
    w: 4,
    h: 2,
    level: 3,
    rarity: 'Legendary',
    night: true,
  },
] as const;
export const UPGRADES = [
  {
    id: 'rod',
    name: 'Fishing gear',
    detail: ['Willow rod', 'Reef reel', 'Deepwater line', 'Starlight rig'],
    cost: [100, 240, 430],
    description: 'Hook stronger fish and widen your safe tension range.',
  },
  {
    id: 'oxygen',
    name: 'Dive equipment',
    detail: [
      'Shallow mask · 20 m',
      'Air tank · 40 m',
      'Pressure suit · 65 m',
      'Abyssal suit · 100 m',
    ],
    cost: [90, 220, 400],
    description: 'Reach deeper treasures with more oxygen.',
  },
  {
    id: 'engine',
    name: 'Boat engine',
    detail: [
      'Little outboard',
      'Coastal motor',
      'Swift engine',
      'Voyager engine',
    ],
    cost: [90, 180, 320],
    description: 'Sail faster and use less fuel.',
  },
  {
    id: 'hold',
    name: 'Cargo hold',
    detail: ['6 × 4 slots', '7 × 4 slots', '8 × 5 slots', '9 × 5 slots'],
    cost: [80, 170, 300],
    description: 'Bring more of the ocean home.',
  },
] as const;
export type UpgradeId = (typeof UPGRADES)[number]['id'];
export const RELICS = [
  {
    id: 'tide',
    name: 'Tide compass',
    x: 68,
    z: -34,
    depth: 18,
    story:
      '“The sea remembers every kindness.” A compass points down, toward the sleeping keeper.',
  },
  {
    id: 'song',
    name: 'Echo conch',
    x: -88,
    z: 36,
    depth: 34,
    story:
      'A song from before the islands rose. The keeper once guided every lost voyager home.',
  },
  {
    id: 'light',
    name: 'Keeper’s lantern',
    x: 26,
    z: -158,
    depth: 72,
    story:
      'The last light of a forgotten city. Three relics can awaken the keeper — or be sold to silence its song.',
  },
];
